server:
  # 应用使用的端口
  port: 8082

# 服务名，用于页面logo显示
nav-name: 团队服务导航

# 是否开启登录功能
login:
  enable: false

# 是否开启页面上进行密码修改，用户只有一个，请谨慎开启
change-password:
  enable: false

# 账号密码
spring:
  security:
    user:
      name: admin
      password: 123456
